
name: Sync to Public Repo
on:
  push:
    branches: [main]  # Trigger on pushes to main
jobs:
  push-to-public:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Private Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to Public
        run: |
          git remote add public https://${{ secrets.SYNC_PAT }}:@github.com/BRANCO-TECH/Mchinji-Secondary-Web-Portal.git
          git push public main --force
