
name: Deploy to Public Repo
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build project
        run: |
          # Add your build commands here (if any)
      - name: Deploy to public repo
        uses: cpina/github-action-push-to-another-repository@v1
        with:
          source-directory: ./build # adjust if needed
          destination-git-username: BRANCO-TECH
          destination-git-email: mwaleb075@gmail.com
          destination-repository-name: BRANCO-TECH/Mchinji-Secondary-Web-Portal
          destination-branch: main
          target-directory: .
          github-token: ${{ secrets.workflowdeploy }}



